# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: jf-311-tracker-api

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: The environment name (dev, prod, etc.)
  DynamoDbTableName:
    Type: String
    Default: Jf311TrackerUsers

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  Jf311TrackerApi:
    Type: AWS::Serverless::Function
    FunctionName: !Sub jf-311-tracker-api-${Environment}-lambda # Dynamic Naming
    Properties:
      Handler: src/index.handler
      Runtime: nodejs24.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: null
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Sub ${DynamoDbTableName}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: 
                - !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:JfGoogleServiceAccount311Tracker-zHdjaU"
                - !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:Jf311TrackerDeepLApiToken-uVXKVQ"
                - !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:JfNycdbWowUser-oVHvqg"
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: 
                - "arn:aws:s3:::justfix-311-checklists/*"
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          DB_TABLE: !Sub ${DynamoDbTableName}
          AWS_REGION_NAME: !Sub ${AWS::Region}
          DB_GSI_PHONE_NAME: gsi_phone
          DB_GSI_BUILDING_ID: gsi_hpdBuildingId
          GOOGLE_SECRET_NAME: JfGoogleServiceAccount311Tracker
          DEEPL_SECRET_NAME: Jf311TrackerDeepLApiToken
          NYCDB_SECRET_NAME: JfNycdbWowUser
          GOOGLE_SPREADSHEET_ID: 1WGSimQE4pr8Zxd0fmSImerzATV_ga6VXKMhFdZGktyI
          GOOGLE_TYPEFORM_SHEET_ID: 190132237
          GOOGLE_VIOLATIONS_SHEET_ID: 867808034
          CHECKLIST_BUCKET: justfix-311-checklists
      Events:
        ApiGETuserComplaints:
          Type: Api
          Properties:
            Path: /complaints/{id}
            Method: GET
        ApiPOSTsrNumbers:
          Type: Api
          Properties:
            Path: /srNumbers
            Method: POST

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${Environment}/