AWSTemplateFormatVersion: 2010-09-09
Description: jf-311-tracker
Transform:
  - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: get-all-items.js
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: put-item.js
  Jf311Tracker:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      MemorySize: 128
      Timeout: 100
      Description: A single Lambda function for all operations for our 311 tracker system.
      Events:
        ServerlessRestApiGETid:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
        ServerlessRestApiPOSTtypeformwebhook:
          Type: Api
          Properties:
            Path: /typeform-webhook
            Method: POST
        ServerlessRestApiGETcomplaintsid:
          Type: Api
          Properties:
            Path: /complaints/{id}
            Method: GET
        ServerlessRestApiPOSTsrnumbers:
          Type: Api
          Properties:
            Path: /sr-numbers
            Method: POST
      CodeUri: src
      Environment:
        Variables:
          # Make table name accessible as environment variable from function code during execution
          JF311TRACKERUSERS_TABLE_NAME: !Ref Jf311TrackerUsers
          JF311TRACKERUSERS_TABLE_ARN: !GetAtt Jf311TrackerUsers.Arn
      Policies:
        # Give Create/Read/Update/Delete Permissions to the SampleTable
        - DynamoDBCrudPolicy:
            TableName: !Ref Jf311TrackerUsers
  Jf311TrackerUsers:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON