import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import {
  DynamoDBDocumentClient,
  GetCommand,
  UpdateCommand,
  QueryCommand,
  ScanCommand,
} from "@aws-sdk/lib-dynamodb";
import {
  SecretsManagerClient,
  GetSecretValueCommand,
} from "@aws-sdk/client-secrets-manager";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import * as deepl from "deepl-node";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";
import { Pool } from "pg";

const config = { region: process.env.AWS_REGION_NAME };

const s3Client = new S3Client(config);
const smClient = new SecretsManagerClient(config);
const ddbClient = new DynamoDBClient(config);
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient);

// Fetch the secret once during the Lambda function's init phase (cold start)
let secretsData;

const getSecrets = async (secretId) => {
  try {
    const command = new GetSecretValueCommand({ SecretId: secretId });
    const response = await smClient.send(command);
    const data = JSON.parse(response.SecretString);
    secretsData = { ...secretsData, ...data };
    console.log("Secret fetched during init phase");
  } catch (error) {
    console.error("Error fetching secret during init:", error);
    throw error; // Terminate function if secret cannot be retrieved
  }
};

await getSecrets(process.env.DEEPL_SECRET_NAME);
await getSecrets(process.env.GOOGLE_SECRET_NAME);
await getSecrets(process.env.NYCDB_SECRET_NAME);

// const deeplClient = new deepl.DeepLClient(secretsData.deeplToken);

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  email: secretsData.client_email,
  key: secretsData.private_key,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const { host, user, database, port, password } = secretsData;
const nycdbPool = new Pool({ host, user, database, port, password });

const VIOLATIONS_START_DATE = "2026-01-01";

// Update Complaints

// const HPD_API_KEY_URL =
//   "https://mspwvw-hpdleov3.nyc.gov/authenticationservice/1.0/api/Apim/token";
// const HPD_COMPLAINTS_URL =
//   "https://mspwvw-hpdleov3.nyc.gov/hpdonline.api/1.0/api/building/complaint/list";

// const getHpdApiKey = async () => {
//   const response = await fetch(HPD_API_KEY_URL, { method: "POST" });
//   const data = await response.json();
//   return data.token;
// };

// const getHpdComplaints = async (buildingId, token) => {
//   const body = {
//     buildingId: buildingId,
//     isCountRequired: true,
//     paging: { pageNumber: 1, pageSize: 1000 },
//     sort: { sortKey: "receivedDate", sortOrder: "desc" },
//   };
//   const response = await fetch(HPD_COMPLAINTS_URL, {
//     method: "POST",
//     body: JSON.stringify(body),
//     headers: {
//       "Content-Type": "application/json",
//       ApiKey: `Bearer ${token}`,
//     },
//   });
//   const data = await response.json();
//   return data.responseData.items;
// };

// const getComplaint = (complaints, srNumber) => {
//   return complaints.find((c) => c.serialNo === srNumber);
// };

// const getDeeplTargetLanguage = (language) => {
//   if (language.length === 2) return language;
//   if (language === "hat") return "ht"; // Haitian Creole
//   if (language === "spa") return "ES-419"; // Spanish (Latin American);
//   if (language === "eng") return "en";
//   return undefined;
// };

/**
 * Scans the DynamoDB table and retrieves all items, handling pagination automatically.
 * @returns {Promise<Array>} A promise that resolves to an array of all items.
 */
const getAllUsers = async () => {
  const allItems = [];
  let exclusiveStartKey = undefined;

  do {
    const scanParams = {
      TableName: process.env.DB_TABLE,
      ExclusiveStartKey: exclusiveStartKey,
    };

    try {
      const command = new ScanCommand(scanParams);
      const response = await ddbDocClient.send(command);

      // 3. Collect the items and check for more results
      if (response.Items) {
        allItems.push(...response.Items);
      }
      exclusiveStartKey = response.LastEvaluatedKey; // Update the start key for the next iteration
    } catch (error) {
      console.error("Error scanning DynamoDB table:", error);
      throw error;
    }
  } while (exclusiveStartKey); // Continue as long as there is a LastEvaluatedKey

  return allItems;
};

// get all users
// restructure by hpdBuildingId
// get hpdApiKey
// for each hpdBuildingId's users
// - call complaints API
// - for each user, for each user complaint:
//   - get complaints from api data, check if status or description changed, set field for status changed and status date
// return all users with data updates
// for each user with change:
// - update database for status fields
// - call textit api to trigger flow for status update notification

// TODO: If api calls fail for key invalid, implement retries on complaints API call and refresh API key, seems like it's good for 30min+ so shouldn't be a problem
// TODO: complaints api gives 1000 rows, so should be enough, but later we could/should implement multiple requests with pagination

const dbUserToSheetsRow = (user) => {
  const row = {
    Phone: user.phone,
    Name: user.fullName,
    Language: user.language3,
    Address: user.address,
    Apartment: user.apartment,
    "HPD Building ID": user.hpdBuildingId,
    "HPD Online": `https://hpdonline.nyc.gov/hpdonline/building/${user.hpdBuildingId}`,
    Pets: user.pets,
    "311 SR Numbers": user.srNumbers.join(", "),
    "Issues Checklist": user.checklistUrl,
  };
  return row;
};

const updateGoogleSheets = async (rows, sheetId, addFitler = true) => {
  try {
    const doc = new GoogleSpreadsheet(
      process.env.GOOGLE_SPREADSHEET_ID,
      serviceAccountAuth,
      {
        retryConfig: {
          limit: 5,
          backoffLimit: 3000,
        },
      },
    );
    await doc.loadInfo(); // loads document properties and worksheets
    const sheet = doc.sheetsById[sheetId];
    await sheet.clearRows({ start: 0 }); // includes header
    const headerValues = Object.keys(rows[0]);
    await sheet.setHeaderRow(headerValues);
    await sheet.addRows(rows);
    if (addFitler) {
      const filter = {
        range: {
          startRowIndex: 0,
          endRowIndex: rows.length + 1,
          startColumnIndex: 0,
          endColumnIndex: Object.keys(rows[0]).length,
        },
      };
      await sheet.setBasicFilter(filter);
    }
    return sheet;
  } catch (err) {
    console.log("error updatinge google sheet:", err);
  }
};

const updateTypeformResponses = async () => {
  try {
    const users = await getAllUsers();

    const rows = users.map((user) => dbUserToSheetsRow(user));

    const sheet = await updateGoogleSheets(
      rows,
      process.env.GOOGLE_TYPEFORM_SHEET_ID,
      true,
    );

    return {
      statusCode: 200,
      body: "Typeform responses updated in google sheet",
    };
  } catch (err) {
    console.log("sheet update failed:", err);
    throw error;
  }
};

const updateViolations = async () => {
  const sql = `
    SELECT
    buildingid AS "HPD Building ID", 
    housenumber || ' ' || streetname || ' '|| borough AS "Address", 
    'https://hpdonline.nyc.gov/hpdonline/building/' || buildingid AS "HPD Online",
    apartment AS "Apartment",
    TO_CHAR(inspectiondate, 'YYY-MM-DD') AS "Inspection Date", 
    TO_CHAR(novissueddate, 'YYY-MM-DD') AS "Violation Issued", 
    violationstatus AS "Status",
    currentstatus AS "Current Status",
    TO_CHAR(currentstatusdate, 'YYY-MM-DD') "Current Status Date", 
    novdescription AS "Violation Description"
  FROM pinnacle_buildingids
  INNER JOIN hpd_violations USING(buildingid)
  WHERE inspectiondate > '${VIOLATIONS_START_DATE}'
  ORDER BY inspectiondate DESC;
  `;
  const result = await nycdbPool.query(sql);
  await updateGoogleSheets(result.rows, process.env.GOOGLE_VIOLATIONS_SHEET_ID);
  return;
};

// Get Complaints

const getUserComplaints = async (event) => {
  const params = {
    TableName: process.env.DB_TABLE,
    Key: {
      id: event.pathParameters.id,
    },
  };
  try {
    const command = new GetCommand(params);
    const data = await ddbDocClient.send(command);

    if (data.Item) {
      console.log(
        "Success, item retrieved:",
        JSON.stringify(data.Item, null, 2),
      );

      return {
        statusCode: 200,
        body: "success",
      };
    } else {
      console.log("Item not found");
      return {
        statusCode: 404,
        body: "Item not found",
      };
    }
  } catch (err) {
    console.error("Error retrieving item:", err);
    throw error;
  }
};

// Update Sr Numbers

const getUserByPhone = async (phone) => {
  const params = {
    TableName: process.env.DB_TABLE,
    IndexName: process.env.DB_GSI_PHONE_NAME,
    KeyConditionExpression: `phone = :gsi_val`,
    ExpressionAttributeValues: {
      ":gsi_val": phone,
    },
  };
  try {
    const data = await ddbDocClient.send(new QueryCommand(params));
    console.log("User by phone:", JSON.stringify(data, null, 2));
    if (!data.Items || data.Items.length === 0) {
      console.log("No items found with the GSI key.");
      throw error;
    }
    return data.Items[0];
  } catch (err) {
    console.error("Unable to query GSI. Error:", err);
  }
};

const addSrNumbersForUser = async (event) => {
  const { phone, srNumbers } = JSON.parse(event.body);
  const userData = await getUserByPhone(phone);
  const allSrNumbers = [...srNumbers, ...userData.srNumbers];
  const uniqueSrNumbers = [...new Set(allSrNumbers)];

  const params = {
    TableName: process.env.DB_TABLE,
    Key: {
      id: userData.id,
    },
    UpdateExpression: "set srNumbers = :sr",
    ExpressionAttributeValues: {
      ":sr": uniqueSrNumbers,
    },
    ReturnValues: "UPDATED_NEW",
  };

  let response;
  try {
    const resp = await ddbDocClient.send(new UpdateCommand(params));
    console.log("UpdateItem succeeded:", resp);
    response = {
      statusCode: 200,
      body: "311 Service Request Numbers added to user",
    };
  } catch (err) {
    console.error("Unable to update item. Error:", err);
    response = {
      statusCode: 404,
      body: "Item not found",
    };
  }
  return response;
};

const makeChecklistHtml = (issuesNotes, title, subtitle) => {
  const checklistSections = issuesNotes
    .map((answer) => {
      if (answer.type === "issues") {
        const listItems = answer.value
          .map((issue) => {
            return `<li>
            <label>
                <input type="checkbox">
                ${issue}
            </label>
          </li>`;
          })
          .join("");
        return `<h2>${answer.section}</h2><ul>${listItems}</ul>`;
      } else {
        return `<h3>${answer.section}</h3><p>${answer.value}</p>`;
      }
    })
    .join("");

  const htmlText = `<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>${title}</title>
        <link rel="stylesheet" href="https://justfix-311-checklists.s3.us-east-1.amazonaws.com/checklist-styles-upt.css">
    </head>
    <body>
        <h1>${title}</h1>
        <h2>${subtitle}</h2>
        ${checklistSections}
    </body>
    </html>`;

  return htmlText;
};

export const uploadChecklist = async (
  issuesNotes,
  s3Client,
  title,
  subtitle,
  subdir,
  hash,
) => {
  const checklistHtml = makeChecklistHtml(issuesNotes, title, subtitle);
  const bucket = process.env.CHECKLIST_BUCKET;
  const key = `${subdir}/${hash}/checklist.html`;
  const params = {
    Bucket: bucket,
    Key: key,
    Body: checklistHtml,
    ContentType: "text/html",
    ContentDisposition: "inline",
  };
  const command = new PutObjectCommand(params);
  await s3Client.send(command);

  return `https://${bucket}.s3.us-east-1.amazonaws.com/${key}`;
};

const updateChecklists = async (s3Client) => {
  const users = await getAllUsers();
  const checklistPromises = users.map(async (user) => {
    const title = "UPT 311 Checklist";
    const subtitle = `${user.address} - Apt ${user.apartment}`;
    return uploadChecklist(
      user.issuesNotes,
      s3Client,
      title,
      subtitle,
      "upt",
      user.id,
    );
  });
  await Promise.all(checklistPromises);

  const dbUpdatePromises = users.map(async (user) => {
    const params = {
      TableName: process.env.DB_TABLE,
      Key: {
        id: user.id,
      },
      UpdateExpression: "set checklistUrl = :c",
      ExpressionAttributeValues: {
        ":c": `https://${process.env.CHECKLIST_BUCKET}.s3.us-east-1.amazonaws.com/upt/${user.id}/checklist.html`,
      },
    };

    try {
      const resp = await ddbDocClient.send(new UpdateCommand(params));
      console.log("UpdateItem succeeded:", resp);
    } catch (err) {
      console.error("Unable to update item. Error:", err);
    }
  });
  await Promise.all(dbUpdatePromises);
};

export const handler = async (event) => {
  console.log("EVENT: ", JSON.stringify(event, null, 2));

  const { httpMethod, resource, action } = event;

  try {
    let response;

    if (action === "updateChecklists") {
      try {
        await updateChecklists(s3Client);
        await updateTypeformResponses();
      } catch (err) {
        console.error("checklists update failed", error);
      }
      response = {
        statusCode: 200,
        body: "Checklists regenerated on S3 and updated in DB",
      };
    } else if (action === "updateUptSheets") {
      // Eventbridge schedule
      try {
        await updateTypeformResponses();
      } catch (err) {
        console.error("typeform sheet update failed", error);
      }
      try {
        await updateViolations();
      } catch (err) {
        console.error("violations sheet update failed", error);
      }
      response = {
        statusCode: 200,
        body: "UPT Google Sheet updated",
      };
    } else if (httpMethod === "POST" && resource === "/srNumbers") {
      response = await addSrNumbersForUser(event);
    } else if (httpMethod === "GET" && resource === "/complaints/{id}") {
      response = await getUserComplaints(event);
    } else {
      response = {
        statusCode: 404,
        body: "Resource does not exist",
      };
    }

    return response;
  } catch (error) {
    console.error("ERROR: ", error);
    throw error; // Terminate function if secret cannot be retrieved
  }
};
