import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
import {
  DynamoDBDocumentClient,
  GetCommand,
  UpdateCommand,
  QueryCommand,
} from "@aws-sdk/lib-dynamodb";
import {
  SecretsManagerClient,
  GetSecretValueCommand,
} from "@aws-sdk/client-secrets-manager";
import * as deepl from "deepl-node";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

const config = { region: process.env.AWS_REGION_NAME };

const smClient = new SecretsManagerClient(config);
const ddbClient = new DynamoDBClient(config);
const ddbDocClient = DynamoDBDocumentClient.from(ddbClient);

// Fetch the secret once during the Lambda function's init phase (cold start)
let secretsData;

const getSecrets = async (secretId) => {
  try {
    const command = new GetSecretValueCommand({ SecretId: secretId });
    const response = await smClient.send(command);
    const data = JSON.parse(response.SecretString);
    secretsData = { ...secretsData, ...data };
    console.log("Secret fetched during init phase");
  } catch (error) {
    console.error("Error fetching secret during init:", error);
    throw error; // Terminate function if secret cannot be retrieved
  }
};

await getSecrets(process.env.DEEPL_SECRET_NAME);
await getSecrets(process.env.GOOGLE_SECRET_NAME);

const deeplClient = new deepl.DeepLClient(secretsData.deeplToken);

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  email: secretsData.client_email,
  key: secretsData.private_key,
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

const updateGoogleSheets = async () => {
    try {
  const doc = new GoogleSpreadsheet(
    process.env.GOOGLE_SPREADSHEET_ID,
    serviceAccountAuth,
    {
      retryConfig: {
        limit: 5,
        backoffLimit: 3000,
      },
    },
  );
  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsById[process.env.GOOGLE_SHEET_ID];
  await sheet.clearRows({ start: 0 }); // includes header
  await sheet.setHeaderRow([
    "phone",
    "name",
    "address",
    "apartment",
    "311 SR Number",
    "status",
    "status description",
    "status description translated",
  ]);
  const sampleRow = {
    phone: "test",
    name: "test",
    address: "test",
    apartment: "test",
    "311 SR Number": "test",
    status: "test",
    "status description": "test",
    "status description translated": "test",
  };
  await sheet.addRows([sampleRow]);
} catch (err) {
    console.log("error updatinge google sheet:", err)
}
};

const getUserComplaints = async (event) => {
  const params = {
    TableName: process.env.DB_TABLE,
    Key: {
      id: event.pathParameters.id,
    },
  };
  try {
    const command = new GetCommand(params);
    const data = await ddbDocClient.send(command);

    if (data.Item) {
      console.log(
        "Success, item retrieved:",
        JSON.stringify(data.Item, null, 2),
      );

      return {
        statusCode: 200,
        body: "success",
      };
    } else {
      console.log("Item not found");
      return {
        statusCode: 404,
        body: "Item not found",
      };
    }
  } catch (err) {
    console.error("Error retrieving item:", err);
    throw error;
  }
};

const getUserByPhone = async (phone) => {
  const params = {
    TableName: process.env.DB_TABLE,
    IndexName: process.env.DB_GSI_PHONE_NAME,
    KeyConditionExpression: `phone = :gsi_val`,
    ExpressionAttributeValues: {
      ":gsi_val": phone,
    },
  };
  try {
    const data = await ddbDocClient.send(new QueryCommand(params));
    console.log("User by phone:", JSON.stringify(data, null, 2));
    if (!data.Items || data.Items.length === 0) {
      console.log("No items found with the GSI key.");
      throw error;
    }
    return data.Items[0];
  } catch (err) {
    console.error("Unable to query GSI. Error:", err);
  }
};

const addSrNumbersForUser = async (event) => {
  const { phone, srNumbers } = JSON.parse(event.body);
  const userData = await getUserByPhone(phone);
  const allSrNumbers = [...srNumbers, ...userData.srNumbers];
  const uniqueSrNubers = [...new Set(allSrNumbers)];

  const params = {
    TableName: process.env.DB_TABLE,
    Key: {
      id: userData.id,
    },
    UpdateExpression: "set srNumbers = :sr",
    ExpressionAttributeValues: {
      ":sr": uniqueSrNubers,
    },
    ReturnValues: "UPDATED_NEW",
  };

  let response;
  try {
    const resp = await ddbDocClient.send(new UpdateCommand(params));
    console.log("UpdateItem succeeded:", resp);
    response = {
      statusCode: 200,
      body: "311 Service Request Numbers added to user",
    };
  } catch (err) {
    console.error("Unable to update item. Error:", err);
    response = {
      statusCode: 404,
      body: "Item not found",
    };
  }
  return response;
};

const updateComplaintStatus = async () => {
  try {
    await updateGoogleSheets();

    return {
      statusCode: 200,
      body: "Schedule update complaint status",
    };
  } catch (err) {
    console.log("sheet update failed:", err);
    throw error;
  }
};

export const handler = async (event) => {
  console.log("EVENT: ", JSON.stringify(event, null, 2));

  const { httpMethod, resource, action } = event;

  try {
    let response;

    if (action === "updateComplaintStatus") {
      // Eventbridge schedule
      response = await updateComplaintStatus();
    } else if (httpMethod === "POST" && resource === "/srNumbers") {
      response = await addSrNumbersForUser(event);
    } else if (httpMethod === "GET" && resource === "/complaints/{id}") {
      response = await getUserComplaints(event);
    } else {
      response = {
        statusCode: 404,
        body: "Resource does not exist",
      };
    }

    return response;
  } catch (error) {
    console.error("ERROR: ", error);
    throw error; // Terminate function if secret cannot be retrieved
  }
};
